### ISSUE TITLE
Byte Addressing for TypedArray views of heaps - why, and what does it accomplish?

### ISSUE THREAD

**Issue by nphyx** [dherman/asm.js#124]
This is a question, not a bug. I'm trying to understand why this is required, and what the implications are.

Take the following example:
```js
function myModule(stdlib, foreign, buffer) {
  "use asm";
  var heap32 = new stdlib.Uint32Array(buffer);
  var P_MYVAR = 0; // pointer to myvar in heap
  function incrementMyVar() {
    heap32[P_MYVAR<<2>>2] = heap32[P_MYVAR<<2>>2]|0 + 1|0;
  }
  return {incrementMyVar:incrementMyVar};
}
```
The point is to have P_MYVAR act as a pointer to heap32[0]. Why do I need to shift it? If I'm just coercing it to an int type, shouldn't I be able to do something like `~~P_MYVAR` or `P_MYVAR|0`? 

I don't understand the point of shifting, or why different TypedArrays must be shifted differently. Is it just an acknowledgement that I know what kind of TypedArray I'm working with?

Thanks for any insight you can provide. The docs weren't clear on why this requirement existed, so I don't even know whether my workaround is sensible, but it seems unnecessarily verbose.

**Comment by kripken** [comment]
The issue is that the typed arrays alias. Element 0 of the 32-bit heap aliases the same data as the first 4 elements of the 8-bit heap, etc. This is necessary for C and C++ compatibility, and luckily JS typed arrays are capable of it.

Given that aliasing, note that we can only read a 32-bit value at addresses 0, 4, 8, etc. - since the first element is bytes 0-3, second is 4-7, etc. In other words, the pointer must be aligned: 32-bit values are read from addresses that are a multiple of 32 bits.

The shift enforces that: a 32-bit read of `ptr >> 2` means that we read from address `ptr`, but we force it to be aligned. If `ptr` is 4, then we read from element 1, which aliases bytes 4-7, etc. But if we try to do an unaligned read from 5, we also read from the same location, as the shift removes the unaligned bits.

**Comment by nphyx** [comment]
So it's behaving as if `ptr` were assumed to be a byte offset of a raw buffer, rather than an array index? So I can write my "pointers" as offsets like so and save myself a few characters:
```js
...
var P_MYVAR = 0;
var P_MYVAR 2 = 4;
...
heap32[P_MYVAR >>2] = ...
```

What's the advantage of doing it this way vs. just expecting the transpiler to do the math, compile-time performance? I guess people aren't expected to write this by hand very often.

**Comment by kripken** [comment]
Yes, `ptr` is just like a C pointer - it's the actual address.

Doing the shift on each load/store ensures alignment as mentioned before. It also is efficient since when generating machine code you want the actual address, not the JS typed array index.

**Comment by nphyx** [comment]
Gotcha. Thanks for the help :)
